import Navbar from "@/components/Navbar";
import "./globals.css";

export const metadata = {
  title: "Fitness Gym",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
